package olc1.proyecto1_201700521;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author GabrielPaz
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEntrada = new javax.swing.JTextArea();
        btnAnalizar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGEXIVE");

        txtEntrada.setColumns(20);
        txtEntrada.setRows(5);
        jScrollPane2.setViewportView(txtEntrada);

        btnAnalizar.setText("Analizar Entrada");
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        jMenu3.setText("Guardar");

        jMenuItem3.setText("Guardar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Guardar Como");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenu1.add(jMenu3);

        jMenuItem2.setText("Abrir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Mas");

        jMenuItem6.setText("Limpiar Texto");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem5.setText("Salir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnAnalizar)))
                .addContainerGap(351, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAnalizar)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed
    public String Ruta;
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        // Eventos de Archivo "ABRIR"
        JFileChooser jfileC = new JFileChooser();
        jfileC.setFileFilter(new FileNameExtensionFilter("Todos los archivos *.olc", "olc", "OLC"));
        int abrir = jfileC.showDialog(null, "Abrir");
            if (abrir == JFileChooser.APPROVE_OPTION) {
            FileReader FileR = null;
            BufferedReader BufferR = null;
            try {
                File archivo = jfileC.getSelectedFile();
                String ruta= jfileC.getSelectedFile().getAbsolutePath();
                if (ruta.endsWith(".olc") || ruta.endsWith(".OLC") || ruta.endsWith(".Olc")) {
                    FileR = new FileReader(archivo);
                    BufferR = new BufferedReader(FileR);
                    String linea;
                    String contenido = "";
                    Ruta = ruta;
                    txtEntrada.setText(null);
                    while ((linea = BufferR.readLine()) != null) {
                        contenido += linea + "\n";
                    }
                    txtEntrada.setText(contenido);

                } else {
                    JOptionPane.showMessageDialog(this, "El archivo no se logro Abrir", "Error", JOptionPane.ERROR_MESSAGE);
                }

            } catch (FileNotFoundException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        // Evento de Archivo "GUARDAR"
        if(Ruta != null){
            try {
                FileWriter Filew = new FileWriter(Ruta);
                PrintWriter Printw = new PrintWriter(Filew);
                String[] Texto = txtEntrada.getText().split("\n");
                for(String  e: Texto){
                    Printw.println(e);
                }
                Filew.close();
                JOptionPane.showMessageDialog(null, "Se ha guardado Correctamente");
            }catch(IOException e){}
        }else{
            //En caso de que no Exista ruta
            JFileChooser FileC = new JFileChooser();
            FileC.addChoosableFileFilter(new FileNameExtensionFilter("Todos los archivos *.olc", "olc", "OLC"));
            int Seleccionado = FileC.showSaveDialog(null);
            try{
                if (Seleccionado == JFileChooser.APPROVE_OPTION){
                    File JFile =FileC.getSelectedFile();
                    String PATH = JFile.getAbsolutePath();
                    if(!(PATH.endsWith(".olc"))){
                        File temp = new File(PATH+".olc");
                        JFile=temp;
                    }
                    PrintWriter printwriter = new PrintWriter(JFile);
                    printwriter.print(txtEntrada.getText());
                    printwriter.close();


                    Ruta=JFile.getAbsolutePath();
                    System.out.print(Ruta);
                    JOptionPane.showMessageDialog(null, "Se ha guardado Correctamente");
                }
            }catch (Exception e){
                JOptionPane.showMessageDialog(null,"Error al Guardar Archivo", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        // Evento Archivo "GUARDAR COMO"
        JFileChooser FileC = new JFileChooser();
        FileC.addChoosableFileFilter(new FileNameExtensionFilter("Todos los archivos *.olc", "olc", "OLC"));
        int Seleccionado = FileC.showSaveDialog(null);
        try{
            if (Seleccionado == JFileChooser.APPROVE_OPTION){
                File JFile =FileC.getSelectedFile();
                String PATH = JFile.getAbsolutePath();
                if(!(PATH.endsWith(".olc"))){
                    File temp = new File(PATH+".olc");
                    JFile=temp;
                }
                PrintWriter printwriter = new PrintWriter(JFile);
                printwriter.print(txtEntrada.getText());
                printwriter.close();

                Ruta=JFile.getAbsolutePath();
                System.out.print(Ruta);
                JOptionPane.showMessageDialog(null, "Se ha guardado Correctamente");
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error al Guardar Archivo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        txtEntrada.setText("");
        Ruta="";
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        // TODO add your handling code here:
        //vamos a analizar xd
        if (Ruta.equals("")) {
            JOptionPane.showConfirmDialog(rootPane,"No se ha seleccionado archivo");
        }else{
            analizadores.ASintactico parse;
            try {
                parse = new analizadores.ASintactico(new analizadores.ALexico(new BufferedReader(new FileReader(Ruta))));
                parse.parse(); 
                Manejador.obtenerInstancia().setParse(parse);
                for(ArrayList dato: Manejador.obtenerInstancia().getParse().info){
                    System.out.println(dato.getClass());
                    System.out.println(dato.size());
                    for(Object s: dato){
                        //System.out.println(s.getClass());
                        System.out.println(s);
                        
                    }
                }
            } catch (Exception ex) {
                System.out.println("Error fatal en compilación de entrada.");
                System.out.println("Causa: "+ex.getCause());
            } 
        }
    }//GEN-LAST:event_btnAnalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtEntrada;
    // End of variables declaration//GEN-END:variables
}
