
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CS = 17;
  public static final int MENOS = 4;
  public static final int CADENA = 21;
  public static final int ALTERN = 12;
  public static final int DOSPUNTOS = 10;
  public static final int UNOMAS = 15;
  public static final int CONCAT = 11;
  public static final int CD = 18;
  public static final int CPOS = 14;
  public static final int ID = 19;
  public static final int KLEENE = 13;
  public static final int LLAVEDE = 8;
  public static final int MAYOR = 5;
  public static final int EOF = 0;
  public static final int INTERV = 20;
  public static final int DOBPOR = 9;
  public static final int CONJ = 2;
  public static final int error = 1;
  public static final int LLAVEIZ = 7;
  public static final int SALTO = 16;
  public static final int LISTA = 6;
  public static final int PTCOMA = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONJ",
  "PTCOMA",
  "MENOS",
  "MAYOR",
  "LISTA",
  "LLAVEIZ",
  "LLAVEDE",
  "DOBPOR",
  "DOSPUNTOS",
  "CONCAT",
  "ALTERN",
  "KLEENE",
  "CPOS",
  "UNOMAS",
  "SALTO",
  "CS",
  "CD",
  "ID",
  "INTERV",
  "CADENA"
  };
}

